# main.py

import mymodule

name = input("Enter your name: ")
mymodule.greet(name)

base = int(input("Enter base: "))
exp = int(input("Enter exponent: "))

result = mymodule.calculate_power(base, exp)
print("Power =", result)

import mymodule

name = input("Enter your name: ")
mymodule.greet(name)

base = int(input("Enter base: "))
exp = int(input("Enter exponent: "))

result = mymodule.calculate_power(base, exp)

print("Power =", result)


