while True:
    print("\n1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "5":
        print("Exiting Calculator...")
        break

    try:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == "1":
            print("Result =", num1 + num2)

        elif choice == "2":
            print("Result =", num1 - num2)

        elif choice == "3":
            print("Result =", num1 * num2)

        elif choice == "4":
            print("Result =", num1 / num2)

        else:
            print("Invalid choice")

    except ValueError:
        print("Error: Invalid input")

    except ZeroDivisionError:
        print("Error: Cannot divide by zero")

    finally:
        print("Operation attempted.")